global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mclass-server'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*)'
        replacement: 'mclass-server'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 