global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mclass-server'
    static_configs:
      - targets: ['mclass-alb-616483239.ap-northeast-2.elb.amazonaws.com:80']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scheme: 'http'
