global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mclass-server'
    static_configs:
      - targets: ['mclass-alb-616483239.ap-northeast-2.elb.amazonaws.com:80']
    scheme: http
    metrics_path: /metrics
    scrape_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: mclass-server-alb

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
