name: Deploy Express App

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-docker-image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mclass .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mclass

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on:
      - self-hosted
      - prod-1

    steps:
      - name: Create .env file
        run: echo "${{ secrets.ENV_PROD }}" > .env

      - name: Docker Compose Down
        run: sudo docker compose down

      - name: Pull new Docker image and Compose Up
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mclass:latest
          sudo docker compose up -d

      - name: Remove unused images
        run: sudo docker system prune -f
